$ CCP := CC/NoObject/Standard=Portable
$ CCP COMMANDS
$ CCP DISASSEMBLE
$ CCP DISPLACEMENTS
$ CCP GETDATA
$ CCP HEADER
$ CCP INSTRUCTIONS
$ CCP I_TYPE
$ CCP MASKS
$ CCP OPERANDS
$ CCP POSNEG
$ CCP SYMTAB
$ CCP UNDATA
$ CCP UNMACRO
$ Exit